/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Commands.java
 *
 * Created on May 8, 2011, 4:46:09 PM
 */
package minecraftservercontrol;

/**
 *
 * @author Philipp
 */
public class Commands extends javax.swing.JFrame {

    static Minecraft mine;
    
    /** Creates new form Commands */
    public Commands(Minecraft mine) {
        initComponents();
        Commands.mine = mine;
        this.setTitle("Commands");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        help_btn = new javax.swing.JButton();
        kick_btn = new javax.swing.JButton();
        ban_btn = new javax.swing.JButton();
        op_btn = new javax.swing.JButton();
        deop_btn = new javax.swing.JButton();
        banip_btn = new javax.swing.JButton();
        pardonip_btn = new javax.swing.JButton();
        saveall_btn = new javax.swing.JButton();
        say_txt = new javax.swing.JTextField();
        say_btn = new javax.swing.JButton();
        player_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        send_btn = new javax.swing.JButton();
        custom_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        names_ips = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Commands");

        help_btn.setText("Help");
        help_btn.setEnabled(false);
        help_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help_btnActionPerformed(evt);
            }
        });

        kick_btn.setText("Kick");
        kick_btn.setEnabled(false);
        kick_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kick_btnActionPerformed(evt);
            }
        });

        ban_btn.setText("Ban");
        ban_btn.setEnabled(false);
        ban_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ban_btnActionPerformed(evt);
            }
        });

        op_btn.setText("Op");
        op_btn.setEnabled(false);
        op_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_btnActionPerformed(evt);
            }
        });

        deop_btn.setText("Deop");
        deop_btn.setEnabled(false);
        deop_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deop_btnActionPerformed(evt);
            }
        });

        banip_btn.setText("Ban-IP");
        banip_btn.setEnabled(false);
        banip_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banip_btnActionPerformed(evt);
            }
        });

        pardonip_btn.setText("Pardon-IP");
        pardonip_btn.setEnabled(false);
        pardonip_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pardonip_btnActionPerformed(evt);
            }
        });

        saveall_btn.setText("Save all");
        saveall_btn.setEnabled(false);
        saveall_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveall_btnActionPerformed(evt);
            }
        });

        say_btn.setText("Say");
        say_btn.setEnabled(false);
        say_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                say_btnActionPerformed(evt);
            }
        });

        jLabel2.setText("Player/IP");

        send_btn.setText("Send");
        send_btn.setEnabled(false);
        send_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_btnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Custom Command");

        names_ips.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Names", "IPs"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(names_ips);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(91, 91, 91)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(player_txt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 194, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(help_btn)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(kick_btn))
                                    .add(saveall_btn))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(pardonip_btn)
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(ban_btn)
                                            .add(banip_btn))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(op_btn)
                                            .add(deop_btn)))))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(say_txt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 246, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(say_btn))
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(custom_txt)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(send_btn)))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 263, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(player_txt)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(help_btn)
                                            .add(kick_btn))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(saveall_btn))
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(ban_btn)
                                            .add(op_btn))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(banip_btn)
                                            .add(deop_btn))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(pardonip_btn)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(say_txt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(say_btn))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel3)
                                .add(43, 43, 43))
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 177, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(custom_txt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(send_btn)))))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void help_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help_btnActionPerformed
        mine.action("help");
    }//GEN-LAST:event_help_btnActionPerformed

    private void saveall_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveall_btnActionPerformed
        mine.action("save-all");
    }//GEN-LAST:event_saveall_btnActionPerformed

    private void kick_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kick_btnActionPerformed
        mine.action("kick " + player_txt.getText());
    }//GEN-LAST:event_kick_btnActionPerformed

    private void ban_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ban_btnActionPerformed
        mine.action("ban " + player_txt.getText());
    }//GEN-LAST:event_ban_btnActionPerformed

    private void banip_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banip_btnActionPerformed
        mine.action("ban-ip " + player_txt.getText());
    }//GEN-LAST:event_banip_btnActionPerformed

    private void pardonip_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pardonip_btnActionPerformed
        mine.action("pardon-ip " + player_txt.getText());
    }//GEN-LAST:event_pardonip_btnActionPerformed

    private void op_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_btnActionPerformed
        mine.action("op " + player_txt.getText());
    }//GEN-LAST:event_op_btnActionPerformed

    private void deop_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deop_btnActionPerformed
        mine.action("deop " + player_txt.getText());
    }//GEN-LAST:event_deop_btnActionPerformed

    private void say_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_say_btnActionPerformed
        mine.action("say " + say_txt.getText());
    }//GEN-LAST:event_say_btnActionPerformed

    private void send_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_btnActionPerformed
        mine.action(custom_txt.getText().toString());
}//GEN-LAST:event_send_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Commands(mine).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ban_btn;
    public javax.swing.JButton banip_btn;
    private javax.swing.JTextField custom_txt;
    public javax.swing.JButton deop_btn;
    public javax.swing.JButton help_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton kick_btn;
    public javax.swing.JTable names_ips;
    public javax.swing.JButton op_btn;
    public javax.swing.JButton pardonip_btn;
    private javax.swing.JTextField player_txt;
    public javax.swing.JButton saveall_btn;
    public javax.swing.JButton say_btn;
    private javax.swing.JTextField say_txt;
    public javax.swing.JButton send_btn;
    // End of variables declaration//GEN-END:variables
}
